/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Connector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Usuarios extends javax.swing.JInternalFrame {
    Connector conn=new Connector();       	
    Connection connection = conn.getConexion();
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    public Usuarios() {
        initComponents();
    }
   public void retrieve(){
        String query = "select * from user";
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Object[] user = new Object[3];
            model = (DefaultTableModel) userTable.getModel();
            while (rs.next()) {
                user[0] = rs.getString("id");
                user[1] = rs.getString("email");                
                user[2] = rs.getInt("password");
                
                
                model.addRow(user);
            }
            userTable.setModel(model);
        } catch (Exception e){
            System.out.println("Error while retrieving data: "+ e.getMessage());
        }
        finally {
            //Esto nos limpia los resultados obtenidos al ejecutar la consulta
            if(rs != null)
            {
                try
                {
                    rs.close();
                }
                catch(SQLException error)
                {
                    error.printStackTrace();
                }
            }
            //Vamos a limpiar la memoria destinada para la consulta
            if(st != null)
            {
                try
                {
                    st.close();
                }
                catch(SQLException error)
                {
                    error.printStackTrace();
                }
            }
            //Vamos a cerrar la conexión
            if(connection != null)
            {
                try
                {
                    connection.close();
                }
                catch(SQLException error)
                {
                    error.printStackTrace();
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        insertar = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        eliminartodobtn = new javax.swing.JButton();
        modificarbtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "email", "password"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        insertar.setText("Ver Usuarios");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        eliminarbtn.setText("eliminar");

        eliminartodobtn.setText("eliminar todo");
        eliminartodobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminartodobtnActionPerformed(evt);
            }
        });

        modificarbtn.setText("modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertar)
                .addGap(18, 18, 18)
                .addComponent(eliminarbtn)
                .addGap(18, 18, 18)
                .addComponent(eliminartodobtn)
                .addGap(18, 18, 18)
                .addComponent(modificarbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertar)
                    .addComponent(eliminarbtn)
                    .addComponent(eliminartodobtn)
                    .addComponent(modificarbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminartodobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminartodobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminartodobtnActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
       retrieve();
    }//GEN-LAST:event_insertarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JButton eliminartodobtn;
    private javax.swing.JButton insertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarbtn;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
